import { getToolBySlug } from '@/data/tools';

export type ToolLinkType = 'internal' | 'external' | 'detail' | 'fallback';

export interface ResolvedToolLink {
  type: ToolLinkType;
  url: string;
  realSlug?: string;
  displayName?: string;
}

export const INTERNAL_TOOL_SLUGS = new Set<string>([
  'audio-bpm-detector',
  'avatar-decorator',
  'base64-tool',
  'caption-generator',
  'case-converter',
  'color-picker',
  'copy-cleaner',
  'countdown',
  'danmaku',
  'decision-wheel',
  'emoji-mixer',
  'fortune-sticks',
  'grid-cutter',
  'image-compressor',
  'image-to-base64',
  'json-formatter',
  'keyword-spinoff-generator',
  'markdown-platform-adapter',
  'markdown-platform-converter',
  'markdown-preview',
  'mortgage-calculator',
  'multi-timezone-publish-time',
  'password-generator',
  'pdf-merger',
  'pinyin-annotator',
  'polyphonic-pinyin-annotator',
  'qr-code-generator',
  'random-number',
  'regex-tester',
  'script-splitter',
  'seo-keyword-miner',
  'sentiment-analyzer',
  'srt-subtitle-generator',
  'text-counter',
  'text-tools',
  'text-to-speech',
  'timestamp-converter',
  'title-weight-checker',
  'url-encode-decode',
  'uuid-generator',
  'vertical-chinese-generator',
  'wallpaper-maker',
  'wc-2026-schedule',
  'wc-ascii-art',
  'wc-champion-predictor',
  'wc-fan-avatar',
  'wc-name-decorator',
  'wc-poster-generator',
  'wc-scoreboard-simulator',
  'excel-formula-generator',
  'task-breakdown',
  'tone-changer',
  'focus-timer',
  'concept-explain',
  'idea-to-action',
  'time-estimator',
]);

export const SLUG_ALIAS: Record<string, string> = {
  'base64-encoder': 'base64-tool',
  'base64-decoder': 'base64-tool',
  'base64': 'base64-tool',
  'url-encoder': 'url-encode-decode',
  'url-decoder': 'url-encode-decode',
  'urlencode': 'url-encode-decode',
  'regex101': 'regex-tester',
  'regex': 'regex-tester',
  'pomodoro-timer': 'countdown',
  'pomodoro': 'countdown',
  'tomato-timer': 'countdown',
  'focus-timer': 'countdown',
  'image-compress': 'image-compressor',
  'compress-image': 'image-compressor',
  'pdf-merge': 'pdf-merger',
  'merge-pdf': 'pdf-merger',
  'json': 'json-formatter',
  'json-formatter-online': 'json-formatter',
  'qr-code': 'qr-code-generator',
  'qrcode': 'qr-code-generator',
  'password': 'password-generator',
  'random-password': 'password-generator',
  'uuid': 'uuid-generator',
  'uuid-generate': 'uuid-generator',
  'pinyin': 'pinyin-annotator',
  'pinyin-annotation': 'pinyin-annotator',
  'zhuyin': 'pinyin-annotator',
  'random': 'random-number',
  'rng': 'random-number',
  'timestamp': 'timestamp-converter',
  'unix-timestamp': 'timestamp-converter',
  'time-converter': 'timestamp-converter',
  'emoji': 'emoji-mixer',
  'emoji-mix': 'emoji-mixer',
  'color': 'color-picker',
  'color-palette': 'color-picker',
  'case': 'case-converter',
  'case-convert': 'case-converter',
  'counter': 'text-counter',
  'char-counter': 'text-counter',
  'word-counter': 'text-counter',
  'markdown': 'markdown-preview',
  'md-preview': 'markdown-preview',
  'tts': 'text-to-speech',
  'text2speech': 'text-to-speech',
  'sentiment': 'sentiment-analyzer',
  'sentiment-analysis': 'sentiment-analyzer',
  'caption': 'caption-generator',
  'subtitle': 'caption-generator',
  'avatar': 'avatar-decorator',
  'pfp': 'avatar-decorator',
  'image-grid': 'grid-cutter',
  'grid-split': 'grid-cutter',
  'wallpaper': 'wallpaper-maker',
  'bg-maker': 'wallpaper-maker',
  'script-split': 'script-splitter',
  'copy': 'copy-cleaner',
  'formatting-cleaner': 'copy-cleaner',
  'title-check': 'title-weight-checker',
  'headline-checker': 'title-weight-checker',
  'keyword': 'keyword-spinoff-generator',
  'seo-keyword': 'keyword-spinoff-generator',
  'markdown-adapter': 'markdown-platform-adapter',
  'md-converter': 'markdown-platform-adapter',
  'vertical-text': 'vertical-chinese-generator',
  'vertical-chinese': 'vertical-chinese-generator',
  'mortgage': 'mortgage-calculator',
  'loan-calculator': 'mortgage-calculator',
  'image2base64': 'image-to-base64',
  'img-base64': 'image-to-base64',
  'fortune': 'fortune-sticks',
  'chinese-fortune': 'fortune-sticks',
  'lucky': 'fortune-sticks',
  'decision': 'decision-wheel',
  'picker-wheel': 'decision-wheel',
  'random-decision': 'decision-wheel',
  'danmaku-maker': 'danmaku',
  'bullet-screen': 'danmaku',
  'countdown-timer': 'countdown',
  'deadline': 'countdown',
};

export const EXTERNAL_TOOL_URLS: Record<string, string> = {
  'canva': 'https://www.canva.com',
  'coolors': 'https://coolors.co',
  'unsplash': 'https://unsplash.com',
  'flaticon': 'https://www.flaticon.com',
  'tinypng': 'https://tinypng.com',
  'remove-bg': 'https://www.remove.bg',
  'photopea': 'https://www.photopea.com',
  'image-format-converter': 'https://cloudconvert.com/image-converter',
  'ilovepdf': 'https://www.ilovepdf.com',
  'smallpdf': 'https://smallpdf.com',
  'deepl': 'https://www.deepl.com/translator',
  'codecademy': 'https://www.codecademy.com',
  'copy-ai': 'https://www.copy.ai',
  'buffer': 'https://buffer.com',
  'wikipedia': 'https://www.wikipedia.org',
  'runway': 'https://runwayml.com',
  'runwayml': 'https://runwayml.com',
  'capcut': 'https://www.capcut.com',
  'jianying': 'https://www.capcut.com',
  'remove-music': 'https://www.lalal.ai',
  'lalal': 'https://www.lalal.ai',
  'vocal-remover': 'https://www.lalal.ai',
  'elevenlabs': 'https://elevenlabs.io',
  'eleven-labs': 'https://elevenlabs.io',
  'notion': 'https://www.notion.so',
  'trello': 'https://trello.com',
  'google-docs': 'https://docs.google.com',
  'googledocs': 'https://docs.google.com',
  'grammarly': 'https://www.grammarly.com',
  'dribbble': 'https://dribbble.com',
  'figma': 'https://www.figma.com',
  'shopify': 'https://www.shopify.com',
  'chatgpt': 'https://chat.openai.com',
  'openai': 'https://chat.openai.com',
  'gpt': 'https://chat.openai.com',
  'fiverr': 'https://www.fiverr.com',
  'tiktok': 'https://www.tiktok.com',
  'douyin': 'https://www.tiktok.com',
  'midjourney': 'https://www.midjourney.com',
  'mj': 'https://www.midjourney.com',
  'vercel': 'https://vercel.com',
  'slack': 'https://slack.com',
  'github': 'https://github.com',
  'chatpdf': 'https://www.chatpdf.com',
  'notion-ai': 'https://www.notion.so/product/ai',
  'feishu': 'https://www.feishu.cn',
  'lark': 'https://www.larksuite.com',
  'wechat': 'https://weixin.qq.com',
  'weixin': 'https://weixin.qq.com',
  'dingtalk': 'https://www.dingtalk.com',
  'cross-border-finance': 'https://www.xero.com',
  'cross-border-listing': 'https://www.shopify.com',
  'fiverr-proposal': 'https://www.fiverr.com',
  'product-image-ai': 'https://www.remove.bg',
  'video-pipeline': 'https://www.capcut.com',
  'multilingual-cs': 'https://www.deepl.com/translator',
  'wevideo': 'https://www.wevideo.com',
  'clipchamp': 'https://clipchamp.com',
  'hippo-video': 'https://www.hippovideo.io',
  'renderforest': 'https://www.renderforest.com',
  'animaker': 'https://www.animaker.com',
  'descript': 'https://www.descript.com',
  'tella-tv': 'https://www.tella.tv',
  'animoto': 'https://animoto.com',
  'biteable': 'https://biteable.com',
  'wave-video': 'https://wave.video',
  'playplay': 'https://playplay.com',
  'powtoon': 'https://www.powtoon.com',
  'rawshorts': 'https://www.rawshorts.com',
  'flixier': 'https://flixier.com',
  'vidyard': 'https://www.vidyard.com',
  'typito': 'https://typito.com',
  'movavi': 'https://www.movavi.com',
  'headliner': 'https://www.headliner.app',
  'postman-api': 'https://www.postman.com',
  'swagger-ui': 'https://swagger.io',
  'sentry-io': 'https://sentry.io',
  'apidog': 'https://apidog.com',
  'baidu-ocr': 'https://ai.baidu.com/tech/ocr',
  'tencent-ai': 'https://ai.qq.com',
  'aliyun-ai': 'https://ai.aliyun.com',
  'squoosh-app': 'https://squoosh.app',
  'picresize': 'https://picresize.com',
  'lunapic': 'https://www1.lunapic.com',
  'befunky': 'https://www.befunky.com',
  'pdf24-tools': 'https://tools.pdf24.org',
  'pdf-cafe': 'https://pdfcandy.com',
  'dopdf': 'https://www.dopdf.com',
  'pdfexpert': 'https://pdfexpert.com',
  'bilibili-creator': 'https://member.bilibili.com',
  '9gag': 'https://9gag.com',
  'ted-talks': 'https://www.ted.com',
  'todoist': 'https://todoist.com',
  'evernote': 'https://evernote.com',
  'ticktick': 'https://ticktick.com',
  'obsidian-md': 'https://obsidian.md',
  'crello': 'https://create.vista.com',
  'placeit': 'https://placeit.net',
  'designrr': 'https://designrr.io',
  'logaster': 'https://www.logaster.com',
  'shopee-seller': 'https://seller.shopee.cn',
  'amazon-seller': 'https://sellercentral.amazon.com',
  'woocommerce': 'https://woocommerce.com',
  'bigcommerce': 'https://www.bigcommerce.com',
  'quillbot': 'https://quillbot.com',
  'prowritingaid': 'https://prowritingaid.com',
  'scribens': 'https://www.scribens.com',
  'hubspot-free': 'https://www.hubspot.com',
  'mailchimp': 'https://mailchimp.com',
  'getresponse': 'https://www.getresponse.com',
  'semrush-free': 'https://www.semrush.com',
  'mangools': 'https://mangools.com',
  'seo-review-tools': 'https://www.seoreviewtools.com',
  'later-app': 'https://later.com',
  'planoly': 'https://www.planoly.com',
  'hootsuite': 'https://hootsuite.com',
  'intercom': 'https://www.intercom.com',
  'helpscout': 'https://www.helpscout.com',
  'livechat': 'https://www.livechat.com',
  'expensify': 'https://www.expensify.com',
  'freshbooks': 'https://www.freshbooks.com',
  'xero': 'https://www.xero.com',
  'workday': 'https://www.workday.com',
  'lever-co': 'https://www.lever.co',
  'zoho-people': 'https://www.zoho.com/people/',
  'khan-academy': 'https://www.khanacademy.org',
  'coursera': 'https://www.coursera.org',
  'edx': 'https://www.edx.org',
  'duolingo': 'https://www.duolingo.com',
  'webmd': 'https://www.webmd.com',
  'myfitnesspal': 'https://www.myfitnesspal.com',
  'meetup': 'https://www.meetup.com',
  'imdb': 'https://www.imdb.com',
  'rottentomatoes': 'https://www.rottentomatoes.com',
  'audacity-tutorial': 'https://www.audacityteam.org',
  'audio-mass': 'https://audiomass.co',
  'twisted-wave': 'https://twistedwave.com',
  'sketchfab': 'https://sketchfab.com',
  'vectary': 'https://www.vectary.com',
  'spline-3d': 'https://spline.design',
  'flourish-studio': 'https://flourish.studio',
  'datawrapper': 'https://www.datawrapper.de',
  'infogram': 'https://infogram.com',
  'have-i-been-pwned': 'https://haveibeenpwned.com',
  'virus-total': 'https://www.virustotal.com',
  'urlscan-io': 'https://urlscan.io',
  'miro-board': 'https://miro.com',
  'clickup': 'https://clickup.com',
  'asana': 'https://asana.com',
  'basecamp': 'https://basecamp.com',
  'zip-extractor': 'https://extract.me',
  'cloudconvert-extra': 'https://cloudconvert.com',
  'online-ocr': 'https://www.onlineocr.net',
  'promo-video-maker': 'https://promo.com',
  'magisto-ai-video': 'https://www.magisto.com',
  'dropbox-paper': 'https://www.dropbox.com/paper',
};

const EXTERNAL_DISPLAY_NAMES: Record<string, string> = {
  'canva': 'Canva',
  'coolors': 'Coolors',
  'unsplash': 'Unsplash',
  'flaticon': 'Flaticon',
  'tinypng': 'TinyPNG',
  'remove-bg': 'Remove.bg',
  'photopea': 'Photopea',
  'image-format-converter': 'CloudConvert',
  'ilovepdf': 'iLovePDF',
  'smallpdf': 'Smallpdf',
  'deepl': 'DeepL',
  'codecademy': 'Codecademy',
  'copy-ai': 'Copy.ai',
  'buffer': 'Buffer',
  'wikipedia': 'Wikipedia',
  'runway': 'Runway',
  'runwayml': 'Runway',
  'capcut': 'CapCut',
  'jianying': 'CapCut',
  'remove-music': 'Lalal.ai',
  'lalal': 'Lalal.ai',
  'vocal-remover': 'Lalal.ai',
  'elevenlabs': 'ElevenLabs',
  'eleven-labs': 'ElevenLabs',
  'notion': 'Notion',
  'trello': 'Trello',
  'google-docs': 'Google Docs',
  'googledocs': 'Google Docs',
  'grammarly': 'Grammarly',
  'dribbble': 'Dribbble',
  'figma': 'Figma',
  'shopify': 'Shopify',
  'chatgpt': 'ChatGPT',
  'openai': 'OpenAI',
  'gpt': 'ChatGPT',
  'fiverr': 'Fiverr',
  'tiktok': 'TikTok',
  'douyin': 'TikTok',
  'midjourney': 'Midjourney',
  'mj': 'Midjourney',
  'vercel': 'Vercel',
  'slack': 'Slack',
  'github': 'GitHub',
  'chatpdf': 'ChatPDF',
  'notion-ai': 'Notion AI',
  'feishu': '飞书',
  'lark': 'Lark',
  'wechat': '微信',
  'weixin': '微信',
  'dingtalk': '钉钉',
  'wevideo': 'WeVideo',
  'clipchamp': 'Clipchamp',
  'hippo-video': 'Hippo Video',
  'renderforest': 'Renderforest',
  'animaker': 'Animaker',
  'descript': 'Descript',
  'tella-tv': 'Tella',
  'animoto': 'Animoto',
  'biteable': 'Biteable',
  'wave-video': 'Wave.video',
  'playplay': 'PlayPlay',
  'powtoon': 'Powtoon',
  'rawshorts': 'RawShorts',
  'flixier': 'Flixier',
  'vidyard': 'Vidyard',
  'typito': 'Typito',
  'movavi': 'Movavi',
  'headliner': 'Headliner',
  'postman-api': 'Postman',
  'swagger-ui': 'Swagger',
  'sentry-io': 'Sentry',
  'apidog': 'Apifox',
  'baidu-ocr': '百度OCR',
  'tencent-ai': '腾讯AI',
  'aliyun-ai': '阿里云AI',
  'squoosh-app': 'Squoosh',
  'picresize': 'PicResize',
  'lunapic': 'LunaPic',
  'befunky': 'BeFunky',
  'pdf24-tools': 'PDF24',
  'pdf-cafe': 'PDF Candy',
  'dopdf': 'doPDF',
  'pdfexpert': 'PDF Expert',
  'bilibili-creator': 'B站创作中心',
  '9gag': '9GAG',
  'ted-talks': 'TED',
  'todoist': 'Todoist',
  'evernote': 'Evernote',
  'ticktick': 'TickTick',
  'obsidian-md': 'Obsidian',
  'crello': 'VistaCreate',
  'placeit': 'Placeit',
  'designrr': 'Designrr',
  'logaster': 'Logaster',
  'shopee-seller': 'Shopee Seller',
  'amazon-seller': 'Amazon Seller',
  'woocommerce': 'WooCommerce',
  'bigcommerce': 'BigCommerce',
  'quillbot': 'QuillBot',
  'prowritingaid': 'ProWritingAid',
  'scribens': 'Scribens',
  'hubspot-free': 'HubSpot',
  'mailchimp': 'Mailchimp',
  'getresponse': 'GetResponse',
  'semrush-free': 'Semrush',
  'mangools': 'Mangools',
  'seo-review-tools': 'SEO Review Tools',
  'later-app': 'Later',
  'planoly': 'Planoly',
  'hootsuite': 'Hootsuite',
  'intercom': 'Intercom',
  'helpscout': 'Help Scout',
  'livechat': 'LiveChat',
  'expensify': 'Expensify',
  'freshbooks': 'FreshBooks',
  'xero': 'Xero',
  'workday': 'Workday',
  'lever-co': 'Lever',
  'zoho-people': 'Zoho People',
  'khan-academy': 'Khan Academy',
  'coursera': 'Coursera',
  'edx': 'edX',
  'duolingo': 'Duolingo',
  'webmd': 'WebMD',
  'myfitnesspal': 'MyFitnessPal',
  'meetup': 'Meetup',
  'imdb': 'IMDb',
  'rottentomatoes': 'Rotten Tomatoes',
  'audacity-tutorial': 'Audacity',
  'audio-mass': 'AudioMass',
  'twisted-wave': 'TwistedWave',
  'sketchfab': 'Sketchfab',
  'vectary': 'Vectary',
  'spline-3d': 'Spline',
  'flourish-studio': 'Flourish',
  'datawrapper': 'Datawrapper',
  'infogram': 'Infogram',
  'have-i-been-pwned': 'Have I Been Pwned',
  'virus-total': 'VirusTotal',
  'urlscan-io': 'urlscan.io',
  'miro-board': 'Miro',
  'clickup': 'ClickUp',
  'asana': 'Asana',
  'basecamp': 'Basecamp',
  'zip-extractor': 'Extract.me',
  'cloudconvert-extra': 'CloudConvert',
  'online-ocr': 'OnlineOCR',
  'promo-video-maker': 'Promo.com',
  'magisto-ai-video': 'Magisto',
  'dropbox-paper': 'Dropbox Paper',
};

export function resolveToolLink(slug: string | undefined | null, locale: string = 'zh'): ResolvedToolLink {
  if (!slug) {
    return { type: 'fallback', url: `/${locale}` };
  }
  const raw = String(slug).trim().toLowerCase();
  if (!raw) {
    return { type: 'fallback', url: `/${locale}` };
  }

  const aliased = SLUG_ALIAS[raw];
  const candidate = aliased || raw;

  if (INTERNAL_TOOL_SLUGS.has(candidate)) {
    return {
      type: 'internal',
      url: `/${locale}/tool/${candidate}`,
      realSlug: candidate,
    };
  }

  const extUrl = EXTERNAL_TOOL_URLS[raw] || (aliased ? EXTERNAL_TOOL_URLS[aliased] : undefined);
  if (extUrl) {
    return {
      type: 'external',
      url: extUrl,
      displayName: EXTERNAL_DISPLAY_NAMES[raw] || (aliased ? EXTERNAL_DISPLAY_NAMES[aliased] : undefined) || raw.toUpperCase(),
    };
  }

  const tool = getToolBySlug(candidate);
  if (tool?.externalUrl) {
    return {
      type: 'external',
      url: tool.externalUrl,
      displayName: tool.name || candidate,
    };
  }

  if (tool) {
    return {
      type: 'detail',
      url: `/${locale}/tool/detail/?slug=${encodeURIComponent(candidate)}`,
      realSlug: candidate,
    };
  }

  return {
    type: 'fallback',
    url: `/${locale}`,
  };
}

export function getToolDisplayLabel(slug: string | undefined | null): string | null {
  if (!slug) return null;
  const raw = String(slug).trim().toLowerCase();
  return EXTERNAL_DISPLAY_NAMES[raw] || getToolBySlug(raw)?.name || null;
}

export function isInternalTool(slug: string | undefined | null): boolean {
  if (!slug) return false;
  const raw = String(slug).trim().toLowerCase();
  const aliased = SLUG_ALIAS[raw] || raw;
  return INTERNAL_TOOL_SLUGS.has(aliased);
}

export function isExternalTool(slug: string | undefined | null): boolean {
  if (!slug) return false;
  const raw = String(slug).trim().toLowerCase();
  const direct = !!EXTERNAL_TOOL_URLS[raw];
  const aliased = !!SLUG_ALIAS[raw] && !!EXTERNAL_TOOL_URLS[SLUG_ALIAS[raw]];
  if (direct || aliased) return true;
  const tool = getToolBySlug(raw);
  return !!tool?.externalUrl;
}
